define dog model
(
  size [1 0.8 0.7]	
   #body
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.25 0 ]
      point[1]  [ 0.75 0 ]
      point[2]  [ 0.75 0.8 ]
      point[3]  [ 0.25 0.8 ]
      z [0.2 0.55]
   )
   #legs
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.25 0 ]
      point[1]  [ 0.35 0 ]
      point[2]  [ 0.35 0.1 ]
      point[3]  [ 0.25 0.1 ]
      z [0 0.2]
   )
   #legs
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.25 0.7 ]
      point[1]  [ 0.35 0.7 ]
      point[2]  [ 0.35 0.8 ]
      point[3]  [ 0.25 0.8 ]
      z [0 0.2]
   )
   #legs
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.65 0.7 ]
      point[1]  [ 0.75 0.7 ]
      point[2]  [ 0.75 0.8 ]
      point[3]  [ 0.65 0.8 ]
      z [0 0.2]
   )
   #legs
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.65 0 ]
      point[1]  [ 0.75 0 ]
      point[2]  [ 0.75 0.1 ]
      point[3]  [ 0.65 0.1 ]
      z [0 0.2]
   )
  #head
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.1 0.20 ]
      point[1]  [ 0.25 0.20 ]
      point[2]  [ 0.25 0.60 ]
      point[3]  [ 0.1 0.60 ]
      z [0.4 0.65]
   )
  #nose
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0 0.25 ]
      point[1]  [ 0.1 0.25 ]
      point[2]  [ 0.1 0.55 ]
      point[3]  [ 0 0.55 ]
      z [0.45 0.55]
   )

  #ears
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.15 0.22 ]
      point[1]  [ 0.20 0.22 ]
      point[2]  [ 0.20 0.35 ]
      point[3]  [ 0.15 0.35 ]
      z [0.65 0.7]
   )
  #ears
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.15 0.45 ]
      point[1]  [ 0.20 0.45 ]
      point[2]  [ 0.20 0.58 ]
      point[3]  [ 0.15 0.58 ]
      z [0.65 0.7]
   )

   #tail
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.75 0.3 ]
      point[1]  [ 1 0.3 ]
      point[2]  [ 1 0.5 ]
      point[3]  [ 0.75 0.5 ]
      z [0.4 0.5]
   )
   #tail
   block 
   (
      color "yellow"
      points 4
      point[0]  [ 0.9 0.3 ]
      point[1]  [ 1 0.3 ]
      point[2]  [ 1 0.5 ]
      point[3]  [ 0.9 0.5 ]
      z [0.2 0.4]
   )


)
