
include "myblock.inc"

tree( pose [ -4 4 0 0 ] ) 
tree( pose [ 4 4 0 0 ] ) 
tree( pose [ -4 8 0 0 ] ) 
tree( pose [ 4 8 0 0 ] ) 
tree( pose [ -2 8 0 0 ] ) 
tree( pose [ 2 8 0 0 ] ) 
tree( pose [ -2 4 0 0 ] ) 
tree( pose [ 2 4 0 0 ] ) 
tree( pose [ 8 8 0 0 ] ) 
tree( pose [ -8 4 0 0 ] ) 
tree( pose [ 6 4 0 0 ] ) 
tree( pose [ 6 8 0 0 ] ) 
tree( pose [ -6 4 0 0 ] ) 
tree( pose [ 6 4 0 0 ] ) 

fence( pose [ 0 2 0 0 ] ) 
fence( pose [ 0 11 0 0 ] ) 
fence1( pose [ 10 6.5 0 0 ] ) 
fence1( pose [ -10 6.5 0 0 ] ) 
