define tree model(	
 	color "green" 
	block( 
	points 4 
	point[0] [0 0] 
	point[1] [1 0] 
	point[2] [1 1] 
	point[3] [0 1]
	z [0 1] )
	
) 


define fence model(
 	color "yellow" 
 	size [20 1 2] 	
	block( 
	points 4 
	point[0] [0 0] 
	point[1] [1 0] 
	point[2] [1 1] 
	point[3] [0 1]
	z [0 1] )
) 

define fence1 model(
 	color "yellow" 
 	size [1 10 2] 	
	block( 
	points 4 
	point[0] [0 0] 
	point[1] [1 0] 
	point[2] [1 1] 
	point[3] [0 1]
	z [0 1] )
) 
